[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
HyperFEM = "ddbf423a-3df4-409e-9685-3dc416cae46c"
HyperShape = "1a07404e-cd44-4b01-9b9c-59424ef2e75e"
